import { createReducer, on } from "@ngrx/store";
import { UserInformation } from "./user-information.model";
import { getUserInformationSuccess } from "./user-information.actions";

export const userInformationFeatureKey = "userInformation";

export interface UserInformationState {
  userInformation: UserInformation;
}

export const initialUserInformationState: UserInformationState = {
  userInformation: {
    fullName: "",
    firstName: "",
    lastName: "",
    emailAddress: "",
    smsAddress: "",
    phoneNumber: "",
    countryCode: "",
    physicalAddress: "",
    city: "",
    state: "",
    postalCode: "",
    timezone: "",
    language: "",
    roles: [],
    permissions: {
      orders: {
        accessOrders: false,
        editOrders: false,
        deleteOrders: false,
        manualCreateEditStandardOrders: false,
        manualCreateEditEmergencyOrders: false,
        manualOverrideCitStandardOptions: false,
        manualPrintOrders: false,
        manualPrintAllFormats: false,
        manualRequestOrders: false,
        manualApproveOrders: false,
        manualRejectOrders: false,
        manualStopApprovedOrders: false,
        manualSendOrders: false,
        automaticEditOrders: false,
        automaticOverrideCitOptions: false,
        automaticPrintOrders: false,
        automaticPrintAllFormats: false,
        automaticRequestOrders: false,
        automaticApproveOrders: false,
        automaticRejectOrders: false,
        automaticStopApprovedOrders: false,
        automaticSendOrders: false,
        accessProvisionalCredit: false,
        accessProvisionalCreditPrintTransferFile: false,
        accessProvisionalCreditPrintTransferFilePrintAllFormats: false,
        accessProvisionalCreditSendTransferFile: false,
      },
      tracking: {
        accessTransaction: false,
        accessTransactionAddComments: false,
        accessTransactionShowSourceData: false,
        accessTransactionAllowAddingTransaction: false,
        accessInventory: false,
        accessInventoryViewPieces: false,
        accessInventoryViewValues: false,
        accessInventoryHistory: false,
      },
      cits: {
        viewCits: false,
        createEditCits: false,
        deleteCits: false,
        viewGeneralSettings: false,
        createEditGeneralSettings: false,
        viewOrdersSettings: false,
        createEditOrdersSettings: false,
        viewServicesSettings: false,
        createEditServicesSettings: false,
        viewLocationsSettings: false,
        createEditLocationsSettings: false,
        viewCalendarsSettings: false,
        createEditCalendarsSettings: false,
        viewProvisionalCreditSettings: false,
        createEditProvisionalCreditSettings: false,
      },
      devices: {
        viewDevices: false,
        createEditDevices: false,
        deleteDevices: false,
      },
      locations: {
        viewLocations: false,
        createEditLocations: false,
        deleteLocations: false,
        viewGeneralSettings: false,
        createEditGeneralSettings: false,
        viewDeviceSettings: false,
        createEditDeviceSettings: false,
        viewCitSettings: false,
        createEditCitSettings: false,
        viewCurrencySettings: false,
        createEditCurrencySettings: false,
        viewCalendarSettings: false,
        createEditCalendarSettings: false,
        viewOrderSettings: false,
        createEditOrderSettings: false,
        viewProvisionalCreditSettings: false,
        createEditProvisionalCreditSettings: false,
      },
      calendars: {
        viewCalendars: false,
        createEditCalendars: false,
        deleteCalendars: false,
        viewServiceSettings: false,
        createEditServiceSettings: false,
        viewServiceLocationsSettings: false,
        createEditServiceLocationsSettings: false,
        viewEmergencySettings: false,
        createEditEmergencySettings: false,
        viewEmergencyLocationsSettings: false,
        createEditEmergencyLocationsSettings: false,
        viewHolidaySettings: false,
        createEditHolidaySettings: false,
        viewHolidayLocationsSettings: false,
        createEditHolidayLocationsSettings: false,
        viewHolidayCitsSettings: false,
        createEditHolidayCitsSettings: false,
      },
      rolesOfInform: {
        viewRoles: false,
        createEditRoles: false,
        deleteRoles: false,
      },
      rolesOfManage: {
        viewRoles: false,
        createEditRoles: false,
        deleteRoles: false,
      },
      schedules: {
        viewSchedules: false,
        createEditSchedules: false,
        deleteSchedules: false,
        viewScheduleOrder: false,
        createEditScheduleOrder: false,
        viewScheduleReport: false,
        createEditScheduleReport: false,
        viewScheduleAlert: false,
        createEditScheduleAlert: false,
        viewGlobalSchedule: false,
        createEditGlobalSchedule: false,
        createEditScheduleProvisionalCredit: false,
        viewScheduleProvisionalCredit: false,
      },
      reporting: {
        accessReports: false,
        accessReportTypes: [],
      },
      widgets: {
        accessWidgets: false,
        accessWidgetTypes: [],
      },
    },
    clientDateTimeFormat: undefined,
    clientDateTimeSecondFormat: undefined,
    clientTimezone: undefined,
    otherApplicationLinks: [],
    accessAbleApplicationIds: [],
  },
};

export const userInformationReducer = createReducer<UserInformationState>(
  initialUserInformationState,
  on(getUserInformationSuccess, (state, { userInformation }) => {
    return {
      userInformation,
    };
  }),
);
