

export class Constant {
  public static readonly defaultLanguage = "default";

  public static components = {
    dashboard: "DashboardPageComponent",
    "view-reports": "ViewReportsPageComponent",
    schedules: "SchedulesPageComponent",
    "edit-schedule": "CreateSchedulePageComponent",
    "create-schedule": "CreateSchedulePageComponent",
  };

  public static conditionPermission = {
    andTrue: "AND-1",
    andFalse: "AND-0",
    orTrue: "OR-1",
    orFalse: "OR-0",
  };

  public static routers = [
    { url: "ordering", router: "/ordering", name: "Ordering", parent: null, permission: "*", groupRole: "" },
    {
      url: "provisional-credit",
      router: "/provisional-credit",
      name: "Provisional Credit",
      parent: "ordering",
      permission: "accessProvisionalCredit",
      groupRole: "orders",
    },
    {
      url: "view-provisional-credit",
      router: "/view-provisional-credit",
      name: "View Provisional Credit",
      parent: "provisional-credit",
      permission: "provisionalCredits",
      groupRole: "orders",
    },
    { url: "orders", router: "/orders", name: "Orders", parent: "ordering", permission: "accessOrders", groupRole: "orders" },
    {
      url: "create-order",
      router: "/create-order",
      name: "Create order",
      parent: "orders",
      permission: "editOrders",
      groupRole: "orders",
    },
    {
      url: "edit-order",
      router: "/edit-order",
      name: "Edit order",
      parent: "orders",
      permission: "accessOrders",
      groupRole: "orders",
    },
    { url: "tracking", router: "/tracking", name: "Tracking", parent: null, permission: "*", groupRole: "" },
    {
      url: "transactions",
      router: "/transactions",
      name: "Transactions",
      parent: "tracking",
      permission: "accessTransaction",
      groupRole: "tracking",
    },
    {
      url: "current-inventory",
      router: "/current-inventory",
      name: "Current Inventory",
      parent: "tracking",
      permission: "accessInventory",
      groupRole: "tracking",
    },
    {
      url: "inventory-history",
      router: "/inventory-history",
      name: "Inventory History",
      parent: "tracking",
      permission: "accessInventoryHistory",
      groupRole: "tracking",
    },
    {
      url: "reporting",
      router: "/reporting",
      name: "Reporting",
      parent: null,
      permission: "accessReports",
      groupRole: "reporting",
    },
    { url: "view-reports", router: "/view-reports", name: null, parent: "reporting", permission: "*", groupRole: "reporting" },
    { url: "setup", router: "/setup", name: "Setup", parent: null, permission: "*", groupRole: "" },
    { url: "calendars", router: "/calendars", name: "Calendars", parent: "setup", permission: "viewCalendars", groupRole: "calendars" },
    {
      url: "create-calendar",
      router: "/create-calendar",
      name: "Create calendar",
      parent: "calendars",
      permission: "createEditCalendars",
      groupRole: "calendars",
    },
    {
      url: "edit-calendar",
      router: "/edit-calendar",
      name: "Edit calendar",
      parent: "calendars",
      permission: "createEditCalendars",
      groupRole: "calendars",
    },
    { url: "cits", router: "/cits", name: "CIT", parent: "setup", permission: "viewCits", groupRole: "cits" },
    {
      url: "create-cit",
      router: "/create-cit",
      name: "Create CIT",
      parent: "cits",
      permission: "createEditCits",
      groupRole: "cits",
    },
    { url: "edit-cit", router: "/edit-cit", name: "Edit CIT", parent: "cits", permission: "createEditCits", groupRole: "cits" },
    { url: "devices", router: "/devices", name: "Devices", parent: "setup", permission: "viewDevices", groupRole: "devices" },
    {
      url: "device-settings",
      router: "/device-settings",
      name: "Device setting",
      parent: "devices",
      permission: "createEditDevices",
      groupRole: "devices",
    },
    { url: "locations", router: "/locations", name: "Locations", parent: "setup", permission: "viewLocations", groupRole: "locations" },
    {
      url: "edit-location",
      router: "/edit-location",
      name: "Edit Location",
      parent: "locations",
      permission: "createEditLocations",
      groupRole: "locations",
    },
    {
      url: "roles-for-manage",
      router: "/roles-for-manage",
      name: "Roles for Manage",
      parent: "setup",
      permission: "viewRoles",
      groupRole: "rolesOfManage",
    },
    {
      url: "roles-for-inform",
      router: "/roles-for-inform",
      name: "Roles for Inform",
      parent: "setup",
      permission: "viewRoles",
      groupRole: "rolesOfInform",
    },
    {
      url: "create-role-manage",
      router: "/create-role-manage",
      name: "Create Role Manage",
      parent: "roles-for-manage",
      permission: "createEditRoles",
      groupRole: "rolesOfManage",
    },
    {
      url: "create-role-inform",
      router: "/create-role-inform",
      name: "Create Role Inform",
      parent: "roles-for-inform",
      permission: "createEditRoles",
      groupRole: "rolesOfInform",
    },
    {
      url: "edit-role-inform",
      router: "/edit-role-inform",
      name: "Edit Role Inform",
      parent: "roles-for-inform",
      permission: "createEditRoles",
      groupRole: "rolesOfInform",
    },
    {
      url: "edit-role-manage",
      router: "/edit-role-manage",
      name: "Edit Role Manage",
      parent: "roles-for-manage",
      permission: "createEditRoles",
      groupRole: "rolesOfManage",
    },
    { url: "schedules", router: "/schedules", name: "Schedules", parent: "setup", permission: "viewSchedules", groupRole: "schedules" },
    {
      url: "create-schedule",
      router: "/create-schedule",
      name: "Create Schedule",
      parent: "schedules",
      permission: "createEditSchedules",
      groupRole: "schedules",
    },
    {
      url: "edit-schedule",
      router: "/edit-schedule",
      name: "Edit Schedule",
      parent: "schedules",
      permission: "createEditSchedules",
      groupRole: "schedules",
    },
  ];
}

