import dayjs from "dayjs";
import timezone from "dayjs/plugin/timezone";
import utc from "dayjs/plugin/utc";
import customParseFormat from "dayjs/plugin/customParseFormat";

dayjs.extend(timezone);
dayjs.extend(utc);
dayjs.extend(customParseFormat);

/**
 * List timezones (Turn on daylight saving time ) (CIT, Location, Schedule) : (timezone(s), fixedTimezone)
 * @property name : for displaying
 * @property timezoneIdentifier : for sending to the backend
 * @property mapping : convert dayjs.tz.guess() => TIMEZONES[timezoneIdentifier]
 */
export const TIMEZONES = [
  {
    name: "(UTC${TZ_OFFSET}) International Date Line West",
    timezoneIdentifier: "Etc/GMT+12",
    mapping: ["Etc/GMT+12"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Coordinated Universal Time-11",
    timezoneIdentifier: "Etc/GMT+11",
    mapping: ["Etc/GMT+11"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Hawaii",
    timezoneIdentifier: "Pacific/Honolulu",
    mapping: ["Pacific/Honolulu", "US/Hawaii", "Pacific/Johnston"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Marquesas Islands",
    timezoneIdentifier: "Pacific/Marquesas",
    mapping: ["Pacific/Marquesas"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Aleutian Islands",
    timezoneIdentifier: "America/Adak",
    mapping: ["America/Adak", "US/Aleutian", "America/Atka"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Coordinated Universal Time-09",
    timezoneIdentifier: "Etc/GMT+9",
    mapping: ["Etc/GMT+9"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Alaska",
    timezoneIdentifier: "America/Anchorage",
    mapping: ["America/Anchorage", "America/Juneau", "America/Metlakatla", "America/Nome", "America/Sitka", "America/Yakutat", "US/Alaska"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Coordinated Universal Time-08",
    timezoneIdentifier: "Etc/GMT+8",
    mapping: ["Etc/GMT+8"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Baja California",
    timezoneIdentifier: "Mexico/BajaNorte",
    mapping: [
      "America/Los_Angeles",
      "US/Pacific",
      "America/Tijuana",
      "Mexico/BajaNorte",
      "America/Ensenada",
      "America/Santa_Isabel",
      "America/Vancouver",
      "Canada/Pacific",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Pacific Time (US and Canada)",
    timezoneIdentifier: "America/Los_Angeles",
    mapping: [
      "America/Los_Angeles",
      "US/Pacific",
      "America/Tijuana",
      "Mexico/BajaNorte",
      "America/Ensenada",
      "America/Santa_Isabel",
      "America/Vancouver",
      "Canada/Pacific",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Arizona",
    timezoneIdentifier: "America/Phoenix",
    mapping: ["America/Phoenix", "US/Arizona", "America/Creston"],
  },
  {
    name: "(UTC${TZ_OFFSET}) La Paz, Mazatlan",
    timezoneIdentifier: "America/Mazatlan",
    mapping: ["America/Hermosillo", "America/Mazatlan", "Mexico/BajaSur"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Yukon",
    timezoneIdentifier: "America/Whitehorse",
    mapping: ["America/Creston", "America/Dawson", "America/Dawson_Creek", "America/Fort_Nelson", "America/Whitehorse", "Canada/Yukon"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Mountain Time (US and Canada)",
    timezoneIdentifier: "America/Denver",
    mapping: [
      "America/Cambridge_Bay",
      "America/Edmonton",
      "America/Inuvik",
      "America/Yellowknife",
      "Canada/Mountain",
      "America/Ciudad_Juarez",
      "America/Boise",
      "America/Denver",
      "Navajo",
      "US/Mountain",
      "America/Shiprock",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Central America",
    timezoneIdentifier: "America/Guatemala",
    mapping: [
      "America/Belize",
      "America/Guatemala",
      "America/Managua",
      "America/Bahia_Banderas",
      "America/Chihuahua",
      "America/Merida",
      "America/Mexico_City",
      "America/Monterrey",
      "Mexico/General",
      "America/Costa_Rica",
      "America/El_Salvador",
      "America/Regina",
      "America/Swift_Current",
      "Canada/Saskatchewan",
      "America/Tegucigalpa",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Easter Island",
    timezoneIdentifier: "Pacific/Easter",
    mapping: ["Pacific/Easter", "Chile/EasterIsland"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Guadalajara, Mexico City, Monterrey",
    timezoneIdentifier: "America/Mexico_City",
    mapping: [
      "America/Belize",
      "America/Guatemala",
      "America/Managua",
      "America/Bahia_Banderas",
      "America/Chihuahua",
      "America/Merida",
      "America/Mexico_City",
      "America/Monterrey",
      "Mexico/General",
      "America/Costa_Rica",
      "America/El_Salvador",
      "America/Regina",
      "America/Swift_Current",
      "Canada/Saskatchewan",
      "America/Tegucigalpa",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Saskatchewan",
    timezoneIdentifier: "America/Regina",
    mapping: [
      "America/Belize",
      "America/Guatemala",
      "America/Managua",
      "America/Bahia_Banderas",
      "America/Chihuahua",
      "America/Merida",
      "America/Mexico_City",
      "America/Monterrey",
      "Mexico/General",
      "America/Costa_Rica",
      "America/El_Salvador",
      "America/Regina",
      "America/Swift_Current",
      "Canada/Saskatchewan",
      "America/Tegucigalpa",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Central Time (US and Canada)",
    timezoneIdentifier: "America/Chicago",
    mapping: [
      "America/Chicago",
      "America/Indiana/Knox",
      "America/Indiana/Tell_City",
      "America/Menominee",
      "America/North_Dakota/Beulah",
      "America/North_Dakota/Center",
      "America/North_Dakota/New_Salem",
      "US/Central",
      "US/Indiana-Starke",
      "America/Knox_IN",
      "America/Matamoros",
      "America/Ojinaga",
      "America/Rankin_Inlet",
      "America/Resolute",
      "America/Winnipeg",
      "Canada/Central",
      "America/Rainy_River",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Bogota, Lima, Quito, Rio Branco",
    timezoneIdentifier: "America/Bogota",
    mapping: ["America/Bogota"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Chetumal",
    timezoneIdentifier: "America/Cancun",
    mapping: [
      "America/Atikokan",
      "America/Cancun",
      "America/Cayman",
      "America/Jamaica",
      "Jamaica",
      "America/Panama",
      "America/Coral_Harbour",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Eastern Time (US and Canada)",
    timezoneIdentifier: "America/New_York",
    mapping: [
      "America/Grand_Turk",
      "America/Nassau",
      "America/Detroit",
      "America/Indiana/Indianapolis",
      "America/Indiana/Marengo",
      "America/Indiana/Petersburg",
      "America/Indiana/Vevay",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Kentucky/Louisville",
      "America/Kentucky/Monticello",
      "America/New_York",
      "US/Michigan",
      "US/East-Indiana",
      "America/Indianapolis",
      "America/Fort_Wayne",
      "America/Louisville",
      "US/Eastern",
      "America/Port-au-Prince",
      "America/Iqaluit",
      "America/Toronto",
      "America/Pangnirtung",
      "Canada/Eastern",
      "America/Montreal",
      "America/Nipigon",
      "America/Thunder_Bay",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Haiti",
    timezoneIdentifier: "America/Port-au-Prince",
    mapping: [
      "America/Grand_Turk",
      "America/Nassau",
      "America/Detroit",
      "America/Indiana/Indianapolis",
      "America/Indiana/Marengo",
      "America/Indiana/Petersburg",
      "America/Indiana/Vevay",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Kentucky/Louisville",
      "America/Kentucky/Monticello",
      "America/New_York",
      "US/Michigan",
      "US/East-Indiana",
      "America/Indianapolis",
      "America/Fort_Wayne",
      "America/Louisville",
      "US/Eastern",
      "America/Port-au-Prince",
      "America/Iqaluit",
      "America/Toronto",
      "America/Pangnirtung",
      "Canada/Eastern",
      "America/Montreal",
      "America/Nipigon",
      "America/Thunder_Bay",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Havana",
    timezoneIdentifier: "America/Havana",
    mapping: ["America/Havana", "Cuba"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Indiana (East)",
    timezoneIdentifier: "America/Indiana/Indianapolis",
    mapping: [
      "America/Grand_Turk",
      "America/Nassau",
      "America/Detroit",
      "America/Indiana/Indianapolis",
      "America/Indiana/Marengo",
      "America/Indiana/Petersburg",
      "America/Indiana/Vevay",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Kentucky/Louisville",
      "America/Kentucky/Monticello",
      "America/New_York",
      "US/Michigan",
      "US/East-Indiana",
      "America/Indianapolis",
      "America/Fort_Wayne",
      "America/Louisville",
      "US/Eastern",
      "America/Port-au-Prince",
      "America/Iqaluit",
      "America/Toronto",
      "America/Pangnirtung",
      "Canada/Eastern",
      "America/Montreal",
      "America/Nipigon",
      "America/Thunder_Bay",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Turks and Caicos",
    timezoneIdentifier: "America/Grand_Turk",
    mapping: [
      "America/Grand_Turk",
      "America/Nassau",
      "America/Detroit",
      "America/Indiana/Indianapolis",
      "America/Indiana/Marengo",
      "America/Indiana/Petersburg",
      "America/Indiana/Vevay",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Kentucky/Louisville",
      "America/Kentucky/Monticello",
      "America/New_York",
      "US/Michigan",
      "US/East-Indiana",
      "America/Indianapolis",
      "America/Fort_Wayne",
      "America/Louisville",
      "US/Eastern",
      "America/Port-au-Prince",
      "America/Iqaluit",
      "America/Toronto",
      "America/Pangnirtung",
      "Canada/Eastern",
      "America/Montreal",
      "America/Nipigon",
      "America/Thunder_Bay",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Asuncion",
    timezoneIdentifier: "America/Asuncion",
    mapping: ["America/Asuncion"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Caracas",
    timezoneIdentifier: "America/Caracas",
    mapping: ["America/Caracas"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Cuiaba",
    timezoneIdentifier: "America/Cuiaba",
    mapping: ["America/Boa_Vista", "America/Campo_Grande", "America/Cuiaba", "America/Manaus", "America/Porto_Velho", "Brazil/West"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Georgetown, La Paz, Manaus, San Juan",
    timezoneIdentifier: "America/La_Paz",
    mapping: ["America/La_Paz"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Santiago",
    timezoneIdentifier: "America/Santiago",
    mapping: ["America/Santiago", "Chile/Continental"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Atlantic Time (Canada)",
    timezoneIdentifier: "America/Halifax",
    mapping: [
      "America/Glace_Bay",
      "America/Goose_Bay",
      "America/Halifax",
      "America/Moncton",
      "Canada/Atlantic",
      "Atlantic/Bermuda",
      "America/Thule",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Araguaina",
    timezoneIdentifier: "America/Araguaina",
    mapping: [
      "America/Araguaina",
      "America/Bahia",
      "America/Belem",
      "America/Fortaleza",
      "America/Maceio",
      "America/Recife",
      "America/Santarem",
      "America/Sao_Paulo",
      "Brazil/East",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Brasilia",
    timezoneIdentifier: "America/Sao_Paulo",
    mapping: [
      "America/Araguaina",
      "America/Bahia",
      "America/Belem",
      "America/Fortaleza",
      "America/Maceio",
      "America/Recife",
      "America/Santarem",
      "America/Sao_Paulo",
      "Brazil/East",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Cayenne, Fortaleza",
    timezoneIdentifier: "America/Fortaleza",
    mapping: [
      "America/Araguaina",
      "America/Bahia",
      "America/Belem",
      "America/Fortaleza",
      "America/Maceio",
      "America/Recife",
      "America/Santarem",
      "America/Sao_Paulo",
      "Brazil/East",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) City of Buenos Aires",
    timezoneIdentifier: "America/Argentina/Buenos_Aires",
    mapping: [
      "America/Argentina/Buenos_Aires",
      "America/Argentina/Catamarca",
      "America/Argentina/Cordoba",
      "America/Argentina/Jujuy",
      "America/Argentina/La_Rioja",
      "America/Argentina/Mendoza",
      "America/Argentina/Rio_Gallegos",
      "America/Argentina/Salta",
      "America/Argentina/San_Juan",
      "America/Argentina/San_Luis",
      "America/Argentina/Tucuman",
      "America/Argentina/Ushuaia",
      "America/Buenos_Aires",
      "America/Catamarca",
      "America/Argentina/ComodRivadavia",
      "America/Cordoba",
      "America/Rosario",
      "America/Jujuy",
      "America/Mendoza",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Montevideo",
    timezoneIdentifier: "America/Montevideo",
    mapping: ["America/Montevideo"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Punta Arenas",
    timezoneIdentifier: "America/Punta_Arenas",
    mapping: ["Antarctica/Palmer", "Antarctica/Rothera", "America/Punta_Arenas"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Salvador",
    timezoneIdentifier: "America/Bahia",
    mapping: [
      "America/Araguaina",
      "America/Bahia",
      "America/Belem",
      "America/Fortaleza",
      "America/Maceio",
      "America/Recife",
      "America/Santarem",
      "America/Sao_Paulo",
      "Brazil/East",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Newfoundland",
    timezoneIdentifier: "America/St_Johns",
    mapping: ["America/St_Johns", "Canada/Newfoundland"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Greenland",
    timezoneIdentifier: "America/Godthab",
    mapping: ["America/Nuuk", "America/Godthab"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Saint Pierre and Miquelon",
    timezoneIdentifier: "America/Miquelon",
    mapping: ["America/Miquelon"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Coordinated Universal Time-02",
    timezoneIdentifier: "Etc/GMT+2",
    mapping: ["Etc/GMT+2"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Cabo Verde Is.",
    timezoneIdentifier: "Atlantic/Cape_Verde",
    mapping: ["Atlantic/Cape_Verde"],
  },
  {
    name: "(UTC) Coordinated Universal Time",
    timezoneIdentifier: "Etc/UTC",
    mapping: ["Etc/GMT", "Etc/UTC", "Etc/UCT", "UCT", "UTC", "Universal", "Zulu"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Azores",
    timezoneIdentifier: "Atlantic/Azores",
    mapping: ["Atlantic/Azores"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Monrovia, Reykjavik",
    timezoneIdentifier: "Africa/Monrovia",
    mapping: [
      "Africa/Abidjan",
      "Iceland",
      "Africa/Accra",
      "Africa/Bamako",
      "Africa/Banjul",
      "Africa/Conakry",
      "Africa/Dakar",
      "Africa/Freetown",
      "Africa/Lome",
      "Africa/Nouakchott",
      "Africa/Ouagadougou",
      "Atlantic/Reykjavik",
      "Atlantic/St_Helena",
      "Africa/Timbuktu",
      "Africa/Bissau",
      "America/Danmarkshavn",
      "Africa/Monrovia",
      "Africa/Sao_Tome",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Sao Tome",
    timezoneIdentifier: "Africa/Sao_Tome",
    mapping: [
      "Africa/Abidjan",
      "Iceland",
      "Africa/Accra",
      "Africa/Bamako",
      "Africa/Banjul",
      "Africa/Conakry",
      "Africa/Dakar",
      "Africa/Freetown",
      "Africa/Lome",
      "Africa/Nouakchott",
      "Africa/Ouagadougou",
      "Atlantic/Reykjavik",
      "Atlantic/St_Helena",
      "Africa/Timbuktu",
      "Africa/Bissau",
      "America/Danmarkshavn",
      "Africa/Monrovia",
      "Africa/Sao_Tome",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Dublin, Edinburgh, Lisbon, London",
    timezoneIdentifier: "Europe/London",
    mapping: [
      "Europe/Isle_of_Man",
      "Europe/Dublin",
      "Eire",
      "Europe/London",
      "GB",
      "GB-Eire",
      "Europe/Guernsey",
      "Europe/Jersey",
      "Europe/Belfast",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Casablanca",
    timezoneIdentifier: "Africa/Casablanca",
    mapping: [
      "Africa/Casablanca",
      "Africa/El_Aaiun",
      "Atlantic/Canary",
      "Atlantic/Madeira",
      "Europe/Lisbon",
      "Portugal",
      "Atlantic/Faroe",
      "Atlantic/Faeroe",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) West Central Africa",
    timezoneIdentifier: "Africa/Lagos",
    mapping: [
      "Africa/Bangui",
      "Africa/Malabo",
      "Africa/Brazzaville",
      "Africa/Porto-Novo",
      "Africa/Douala",
      "Africa/Kinshasa",
      "Africa/Lagos",
      "Africa/Libreville",
      "Africa/Luanda",
      "Africa/Niamey",
      "Africa/Ndjamena",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    timezoneIdentifier: "Europe/Amsterdam",
    mapping: [
      "Europe/Amsterdam",
      "Europe/Andorra",
      "Europe/Belgrade",
      "Europe/Ljubljana",
      "Europe/Podgorica",
      "Europe/Sarajevo",
      "Europe/Skopje",
      "Europe/Zagreb",
      "Europe/Berlin",
      "Europe/Busingen",
      "Arctic/Longyearbyen",
      "Europe/Copenhagen",
      "Europe/Oslo",
      "Europe/Stockholm",
      "Atlantic/Jan_Mayen",
      "Europe/Bratislava",
      "Europe/Brussels",
      "Europe/Luxembourg",
      "Europe/Budapest",
      "Europe/Gibraltar",
      "Africa/Ceuta",
      "Europe/Madrid",
      "Europe/Monaco",
      "Europe/Paris",
      "Europe/Prague",
      "Europe/Rome",
      "Europe/San_Marino",
      "Europe/Vatican",
      "Europe/Malta",
      "Europe/Tirane",
      "Europe/Vaduz",
      "Europe/Vienna",
      "Europe/Warsaw",
      "Poland",
      "Europe/Zurich",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    timezoneIdentifier: "Europe/Belgrade",
    mapping: [
      "Europe/Amsterdam",
      "Europe/Andorra",
      "Europe/Belgrade",
      "Europe/Ljubljana",
      "Europe/Podgorica",
      "Europe/Sarajevo",
      "Europe/Skopje",
      "Europe/Zagreb",
      "Europe/Berlin",
      "Europe/Busingen",
      "Arctic/Longyearbyen",
      "Europe/Copenhagen",
      "Europe/Oslo",
      "Europe/Stockholm",
      "Atlantic/Jan_Mayen",
      "Europe/Bratislava",
      "Europe/Brussels",
      "Europe/Luxembourg",
      "Europe/Budapest",
      "Europe/Gibraltar",
      "Africa/Ceuta",
      "Europe/Madrid",
      "Europe/Monaco",
      "Europe/Paris",
      "Europe/Prague",
      "Europe/Rome",
      "Europe/San_Marino",
      "Europe/Vatican",
      "Europe/Malta",
      "Europe/Tirane",
      "Europe/Vaduz",
      "Europe/Vienna",
      "Europe/Warsaw",
      "Poland",
      "Europe/Zurich",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Brussels, Copenhagen, Madrid, Paris",
    timezoneIdentifier: "Europe/Brussels",
    mapping: [
      "Europe/Amsterdam",
      "Europe/Andorra",
      "Europe/Belgrade",
      "Europe/Ljubljana",
      "Europe/Podgorica",
      "Europe/Sarajevo",
      "Europe/Skopje",
      "Europe/Zagreb",
      "Europe/Berlin",
      "Europe/Busingen",
      "Arctic/Longyearbyen",
      "Europe/Copenhagen",
      "Europe/Oslo",
      "Europe/Stockholm",
      "Atlantic/Jan_Mayen",
      "Europe/Bratislava",
      "Europe/Brussels",
      "Europe/Luxembourg",
      "Europe/Budapest",
      "Europe/Gibraltar",
      "Africa/Ceuta",
      "Europe/Madrid",
      "Europe/Monaco",
      "Europe/Paris",
      "Europe/Prague",
      "Europe/Rome",
      "Europe/San_Marino",
      "Europe/Vatican",
      "Europe/Malta",
      "Europe/Tirane",
      "Europe/Vaduz",
      "Europe/Vienna",
      "Europe/Warsaw",
      "Poland",
      "Europe/Zurich",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Sarajevo, Skopje, Warsaw, Zagreb",
    timezoneIdentifier: "Europe/Sarajevo",
    mapping: [
      "Europe/Amsterdam",
      "Europe/Andorra",
      "Europe/Belgrade",
      "Europe/Ljubljana",
      "Europe/Podgorica",
      "Europe/Sarajevo",
      "Europe/Skopje",
      "Europe/Zagreb",
      "Europe/Berlin",
      "Europe/Busingen",
      "Arctic/Longyearbyen",
      "Europe/Copenhagen",
      "Europe/Oslo",
      "Europe/Stockholm",
      "Atlantic/Jan_Mayen",
      "Europe/Bratislava",
      "Europe/Brussels",
      "Europe/Luxembourg",
      "Europe/Budapest",
      "Europe/Gibraltar",
      "Africa/Ceuta",
      "Europe/Madrid",
      "Europe/Monaco",
      "Europe/Paris",
      "Europe/Prague",
      "Europe/Rome",
      "Europe/San_Marino",
      "Europe/Vatican",
      "Europe/Malta",
      "Europe/Tirane",
      "Europe/Vaduz",
      "Europe/Vienna",
      "Europe/Warsaw",
      "Poland",
      "Europe/Zurich",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Harare, Pretoria",
    timezoneIdentifier: "Africa/Harare",
    mapping: [
      "Africa/Bujumbura",
      "Africa/Gaborone",
      "Africa/Harare",
      "Africa/Juba",
      "Africa/Khartoum",
      "Africa/Kigali",
      "Africa/Blantyre",
      "Africa/Lubumbashi",
      "Africa/Lusaka",
      "Africa/Maputo",
      "Africa/Windhoek",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Juba",
    timezoneIdentifier: "Africa/Juba",
    mapping: [
      "Africa/Bujumbura",
      "Africa/Gaborone",
      "Africa/Harare",
      "Africa/Juba",
      "Africa/Khartoum",
      "Africa/Kigali",
      "Africa/Blantyre",
      "Africa/Lubumbashi",
      "Africa/Lusaka",
      "Africa/Maputo",
      "Africa/Windhoek",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Kaliningrad",
    timezoneIdentifier: "Europe/Kaliningrad",
    mapping: ["Europe/Kaliningrad", "Africa/Tripoli", "Libya"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Khartoum",
    timezoneIdentifier: "Africa/Khartoum",
    mapping: [
      "Africa/Bujumbura",
      "Africa/Gaborone",
      "Africa/Harare",
      "Africa/Juba",
      "Africa/Khartoum",
      "Africa/Kigali",
      "Africa/Blantyre",
      "Africa/Lubumbashi",
      "Africa/Lusaka",
      "Africa/Maputo",
      "Africa/Windhoek",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Tripoli",
    timezoneIdentifier: "Africa/Tripoli",
    mapping: ["Europe/Kaliningrad", "Africa/Tripoli", "Libya"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Windhoek",
    timezoneIdentifier: "Africa/Windhoek",
    mapping: [
      "Africa/Bujumbura",
      "Africa/Gaborone",
      "Africa/Harare",
      "Africa/Juba",
      "Africa/Khartoum",
      "Africa/Kigali",
      "Africa/Blantyre",
      "Africa/Lubumbashi",
      "Africa/Lusaka",
      "Africa/Maputo",
      "Africa/Windhoek",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Athens, Bucharest",
    timezoneIdentifier: "Europe/Athens",
    mapping: [
      "Europe/Athens",
      "Asia/Beirut",
      "Europe/Bucharest",
      "Africa/Cairo",
      "Egypt",
      "Europe/Chisinau",
      "Europe/Tiraspol",
      "Asia/Gaza",
      "Asia/Hebron",
      "Europe/Helsinki",
      "Europe/Mariehamn",
      "Europe/Kyiv",
      "Europe/Uzhgorod",
      "Europe/Zaporozhye",
      "Europe/Kiev",
      "Asia/Famagusta",
      "Asia/Nicosia",
      "Europe/Nicosia",
      "Europe/Riga",
      "Europe/Sofia",
      "Europe/Tallinn",
      "Europe/Vilnius",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Beirut",
    timezoneIdentifier: "Asia/Beirut",
    mapping: [
      "Europe/Athens",
      "Asia/Beirut",
      "Europe/Bucharest",
      "Africa/Cairo",
      "Egypt",
      "Europe/Chisinau",
      "Europe/Tiraspol",
      "Asia/Gaza",
      "Asia/Hebron",
      "Europe/Helsinki",
      "Europe/Mariehamn",
      "Europe/Kyiv",
      "Europe/Uzhgorod",
      "Europe/Zaporozhye",
      "Europe/Kiev",
      "Asia/Famagusta",
      "Asia/Nicosia",
      "Europe/Nicosia",
      "Europe/Riga",
      "Europe/Sofia",
      "Europe/Tallinn",
      "Europe/Vilnius",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Cairo",
    timezoneIdentifier: "Africa/Cairo",
    mapping: [
      "Europe/Athens",
      "Asia/Beirut",
      "Europe/Bucharest",
      "Africa/Cairo",
      "Egypt",
      "Europe/Chisinau",
      "Europe/Tiraspol",
      "Asia/Gaza",
      "Asia/Hebron",
      "Europe/Helsinki",
      "Europe/Mariehamn",
      "Europe/Kyiv",
      "Europe/Uzhgorod",
      "Europe/Zaporozhye",
      "Europe/Kiev",
      "Asia/Famagusta",
      "Asia/Nicosia",
      "Europe/Nicosia",
      "Europe/Riga",
      "Europe/Sofia",
      "Europe/Tallinn",
      "Europe/Vilnius",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Chisinau",
    timezoneIdentifier: "Europe/Chisinau",
    mapping: [
      "Europe/Athens",
      "Asia/Beirut",
      "Europe/Bucharest",
      "Africa/Cairo",
      "Egypt",
      "Europe/Chisinau",
      "Europe/Tiraspol",
      "Asia/Gaza",
      "Asia/Hebron",
      "Europe/Helsinki",
      "Europe/Mariehamn",
      "Europe/Kyiv",
      "Europe/Uzhgorod",
      "Europe/Zaporozhye",
      "Europe/Kiev",
      "Asia/Famagusta",
      "Asia/Nicosia",
      "Europe/Nicosia",
      "Europe/Riga",
      "Europe/Sofia",
      "Europe/Tallinn",
      "Europe/Vilnius",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Damascus",
    timezoneIdentifier: "Asia/Damascus",
    mapping: ["Asia/Damascus"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Gaza, Hebron",
    timezoneIdentifier: "Asia/Gaza",
    mapping: [
      "Europe/Athens",
      "Asia/Beirut",
      "Europe/Bucharest",
      "Africa/Cairo",
      "Egypt",
      "Europe/Chisinau",
      "Europe/Tiraspol",
      "Asia/Gaza",
      "Asia/Hebron",
      "Europe/Helsinki",
      "Europe/Mariehamn",
      "Europe/Kyiv",
      "Europe/Uzhgorod",
      "Europe/Zaporozhye",
      "Europe/Kiev",
      "Asia/Famagusta",
      "Asia/Nicosia",
      "Europe/Nicosia",
      "Europe/Riga",
      "Europe/Sofia",
      "Europe/Tallinn",
      "Europe/Vilnius",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
    timezoneIdentifier: "Europe/Helsinki",
    mapping: [
      "Europe/Athens",
      "Asia/Beirut",
      "Europe/Bucharest",
      "Africa/Cairo",
      "Egypt",
      "Europe/Chisinau",
      "Europe/Tiraspol",
      "Asia/Gaza",
      "Asia/Hebron",
      "Europe/Helsinki",
      "Europe/Mariehamn",
      "Europe/Kyiv",
      "Europe/Uzhgorod",
      "Europe/Zaporozhye",
      "Europe/Kiev",
      "Asia/Famagusta",
      "Asia/Nicosia",
      "Europe/Nicosia",
      "Europe/Riga",
      "Europe/Sofia",
      "Europe/Tallinn",
      "Europe/Vilnius",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Jerusalem",
    timezoneIdentifier: "Asia/Jerusalem",
    mapping: ["Asia/Jerusalem", "Israel", "Asia/Tel_Aviv"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Amman",
    timezoneIdentifier: "Asia/Amman",
    mapping: ["Asia/Amman"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Baghdad",
    timezoneIdentifier: "Asia/Baghdad",
    mapping: ["Asia/Kuwait", "Asia/Bahrain", "Asia/Baghdad", "Asia/Qatar", "Asia/Riyadh", "Antarctica/Syowa", "Asia/Aden"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Istanbul",
    timezoneIdentifier: "Europe/Istanbul",
    mapping: ["Europe/Istanbul", "Turkey", "Asia/Istanbul"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Kuwait, Riyadh",
    timezoneIdentifier: "Asia/Riyadh",
    mapping: ["Asia/Kuwait", "Asia/Bahrain", "Asia/Baghdad", "Asia/Qatar", "Asia/Riyadh", "Antarctica/Syowa", "Asia/Aden"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Minsk",
    timezoneIdentifier: "Europe/Minsk",
    mapping: ["Europe/Minsk", "Europe/Kirov", "Europe/Moscow", "Europe/Volgograd", "W-SU", "Europe/Simferopol"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Moscow, St. Petersburg",
    timezoneIdentifier: "Europe/Moscow",
    mapping: ["Europe/Minsk", "Europe/Kirov", "Europe/Moscow", "Europe/Volgograd", "W-SU", "Europe/Simferopol"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Nairobi",
    timezoneIdentifier: "Africa/Nairobi",
    mapping: [
      "Africa/Addis_Ababa",
      "Indian/Antananarivo",
      "Africa/Asmara",
      "Africa/Dar_es_Salaam",
      "Africa/Djibouti",
      "Africa/Kampala",
      "Indian/Mayotte",
      "Africa/Mogadishu",
      "Indian/Comoro",
      "Africa/Nairobi",
      "Africa/Asmera",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Volgograd",
    timezoneIdentifier: "Europe/Volgograd",
    mapping: ["Europe/Minsk", "Europe/Kirov", "Europe/Moscow", "Europe/Volgograd", "W-SU", "Europe/Simferopol"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Tehran",
    timezoneIdentifier: "Asia/Tehran",
    mapping: ["Asia/Tehran", "Iran"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Abu Dhabi, Muscat",
    timezoneIdentifier: "Asia/Dubai",
    mapping: ["Asia/Dubai", "Asia/Muscat", "Indian/Mahe", "Indian/Reunion"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Astrakhan, Ulyanovsk",
    timezoneIdentifier: "Europe/Astrakhan",
    mapping: ["Europe/Astrakhan", "Europe/Samara", "Europe/Saratov", "Europe/Ulyanovsk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Baku",
    timezoneIdentifier: "Asia/Baku",
    mapping: ["Asia/Baku"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Izhevsk, Samara",
    timezoneIdentifier: "Europe/Samara",
    mapping: ["Europe/Astrakhan", "Europe/Samara", "Europe/Saratov", "Europe/Ulyanovsk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Port Louis",
    timezoneIdentifier: "Indian/Mauritius",
    mapping: ["Indian/Mauritius"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Saratov",
    timezoneIdentifier: "Europe/Saratov",
    mapping: ["Europe/Astrakhan", "Europe/Samara", "Europe/Saratov", "Europe/Ulyanovsk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Tbilisi",
    timezoneIdentifier: "Asia/Tbilisi",
    mapping: ["Asia/Tbilisi"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Yerevan",
    timezoneIdentifier: "Asia/Yerevan",
    mapping: ["Asia/Yerevan"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Kabul",
    timezoneIdentifier: "Asia/Kabul",
    mapping: ["Asia/Kabul"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Ashgabat, Tashkent",
    timezoneIdentifier: "Asia/Ashgabat",
    mapping: ["Asia/Ashgabat", "Asia/Ashkhabad"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Ekaterinburg",
    timezoneIdentifier: "Asia/Yekaterinburg",
    mapping: ["Asia/Yekaterinburg"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Islamabad, Karachi",
    timezoneIdentifier: "Asia/Karachi",
    mapping: ["Asia/Karachi"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Qyzylorda",
    timezoneIdentifier: "Asia/Qyzylorda",
    mapping: ["Asia/Aqtau", "Asia/Aqtobe", "Asia/Atyrau", "Asia/Oral", "Asia/Qyzylorda"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Chennai, Kolkata, Mumbai, New Delhi",
    timezoneIdentifier: "Asia/Kolkata",
    mapping: ["Asia/Colombo", "Asia/Kolkata", "Asia/Calcutta"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Sri Jayawardenepura",
    timezoneIdentifier: "Asia/Colombo",
    mapping: ["Asia/Colombo", "Asia/Kolkata", "Asia/Calcutta"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Kathmandu",
    timezoneIdentifier: "Asia/Kathmandu",
    mapping: ["Asia/Kathmandu", "Asia/Katmandu"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Astana",
    timezoneIdentifier: "Asia/Almaty",
    mapping: ["Asia/Almaty", "Asia/Qostanay"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Dhaka",
    timezoneIdentifier: "Asia/Dhaka",
    mapping: ["Asia/Dhaka", "Asia/Dacca"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Omsk",
    timezoneIdentifier: "Asia/Omsk",
    mapping: ["Asia/Omsk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Yangon (Rangoon)",
    timezoneIdentifier: "Asia/Yangon",
    mapping: ["Asia/Yangon", "Indian/Cocos", "Asia/Rangoon"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Bangkok, Hanoi, Jakarta",
    timezoneIdentifier: "Asia/Bangkok",
    mapping: ["Asia/Bangkok", "Asia/Phnom_Penh", "Asia/Vientiane", "Indian/Christmas", "Asia/Ho_Chi_Minh", "Asia/Saigon"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Barnaul, Gorno-Altaysk",
    timezoneIdentifier: "Asia/Barnaul",
    mapping: ["Asia/Barnaul", "Asia/Krasnoyarsk", "Asia/Novokuznetsk", "Asia/Novosibirsk", "Asia/Tomsk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Hovd",
    timezoneIdentifier: "Asia/Hovd",
    mapping: ["Asia/Hovd"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Krasnoyarsk",
    timezoneIdentifier: "Asia/Krasnoyarsk",
    mapping: ["Asia/Barnaul", "Asia/Krasnoyarsk", "Asia/Novokuznetsk", "Asia/Novosibirsk", "Asia/Tomsk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Novosibirsk",
    timezoneIdentifier: "Asia/Novosibirsk",
    mapping: ["Asia/Barnaul", "Asia/Krasnoyarsk", "Asia/Novokuznetsk", "Asia/Novosibirsk", "Asia/Tomsk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Tomsk",
    timezoneIdentifier: "Asia/Tomsk",
    mapping: ["Asia/Barnaul", "Asia/Krasnoyarsk", "Asia/Novokuznetsk", "Asia/Novosibirsk", "Asia/Tomsk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Beijing, Chongqing, Hong Kong, Urumqi",
    timezoneIdentifier: "Asia/Shanghai",
    mapping: ["Asia/Macau", "Asia/Macao", "Asia/Shanghai", "PRC", "Asia/Chongqing", "Asia/Harbin", "Asia/Chungking"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Irkutsk",
    timezoneIdentifier: "Asia/Irkutsk",
    mapping: ["Asia/Irkutsk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Kuala Lumpur, Singapore",
    timezoneIdentifier: "Asia/Kuala_Lumpur",
    mapping: ["Asia/Kuala_Lumpur", "Asia/Kuching", "Asia/Brunei", "Asia/Singapore", "Singapore", "Asia/Kuala_Lumpur"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Perth",
    timezoneIdentifier: "Australia/Perth",
    mapping: ["Australia/Perth", "Australia/West"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Taipei",
    timezoneIdentifier: "Asia/Taipei",
    mapping: ["Asia/Taipei", "ROC"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Ulaanbaatar",
    timezoneIdentifier: "Asia/Ulaanbaatar",
    mapping: ["Asia/Choibalsan", "Asia/Ulaanbaatar", "Asia/Ulan_Bator"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Eucla",
    timezoneIdentifier: "Australia/Eucla",
    mapping: ["Australia/Eucla"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Chita",
    timezoneIdentifier: "Asia/Chita",
    mapping: ["Asia/Chita", "Asia/Khandyga", "Asia/Yakutsk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Osaka, Sapporo, Tokyo",
    timezoneIdentifier: "Asia/Tokyo",
    mapping: ["Asia/Tokyo", "Japan"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Pyongyang",
    timezoneIdentifier: "Asia/Pyongyang",
    mapping: ["Asia/Pyongyang", "Asia/Seoul", "ROK"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Seoul",
    timezoneIdentifier: "Asia/Seoul",
    mapping: ["Asia/Pyongyang", "Asia/Seoul", "ROK"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Yakutsk",
    timezoneIdentifier: "Asia/Yakutsk",
    mapping: ["Asia/Chita", "Asia/Khandyga", "Asia/Yakutsk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Adelaide",
    timezoneIdentifier: "Australia/Adelaide",
    mapping: [
      "Australia/Adelaide",
      "Australia/Broken_Hill",
      "Australia/South",
      "Australia/Yancowinna",
      "Australia/Darwin",
      "Australia/North",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Darwin",
    timezoneIdentifier: "Australia/Darwin",
    mapping: [
      "Australia/Adelaide",
      "Australia/Broken_Hill",
      "Australia/South",
      "Australia/Yancowinna",
      "Australia/Darwin",
      "Australia/North",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Brisbane",
    timezoneIdentifier: "Australia/Brisbane",
    mapping: [
      "Australia/Brisbane",
      "Australia/Lindeman",
      "Australia/Queensland",
      "Antarctica/Macquarie",
      "Australia/Hobart",
      "Australia/Melbourne",
      "Australia/Sydney",
      "Australia/Tasmania",
      "Australia/Currie",
      "Australia/Victoria",
      "Australia/ACT",
      "Australia/NSW",
      "Australia/Canberra",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Canberra, Melbourne, Sydney",
    timezoneIdentifier: "Australia/Sydney",
    mapping: [
      "Australia/Brisbane",
      "Australia/Lindeman",
      "Australia/Queensland",
      "Antarctica/Macquarie",
      "Australia/Hobart",
      "Australia/Melbourne",
      "Australia/Sydney",
      "Australia/Tasmania",
      "Australia/Currie",
      "Australia/Victoria",
      "Australia/ACT",
      "Australia/NSW",
      "Australia/Canberra",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Guam, Port Moresby",
    timezoneIdentifier: "Pacific/Guam",
    mapping: ["Pacific/Guam", "Pacific/Saipan"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Hobart",
    timezoneIdentifier: "Australia/Hobart",
    mapping: [
      "Australia/Brisbane",
      "Australia/Lindeman",
      "Australia/Queensland",
      "Antarctica/Macquarie",
      "Australia/Hobart",
      "Australia/Melbourne",
      "Australia/Sydney",
      "Australia/Tasmania",
      "Australia/Currie",
      "Australia/Victoria",
      "Australia/ACT",
      "Australia/NSW",
      "Australia/Canberra",
    ],
  },
  {
    name: "(UTC${TZ_OFFSET}) Vladivostok",
    timezoneIdentifier: "Asia/Vladivostok",
    mapping: ["Asia/Ust-Nera", "Asia/Vladivostok"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Lord Howe Island",
    timezoneIdentifier: "Australia/Lord_Howe",
    mapping: ["Australia/Lord_Howe", "Australia/LHI"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Bougainville Island",
    timezoneIdentifier: "Pacific/Bougainville",
    mapping: ["Pacific/Bougainville"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Chokurdakh",
    timezoneIdentifier: "Asia/Srednekolymsk",
    mapping: ["Asia/Magadan", "Asia/Sakhalin", "Asia/Srednekolymsk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Magadan",
    timezoneIdentifier: "Asia/Magadan",
    mapping: ["Asia/Magadan", "Asia/Sakhalin", "Asia/Srednekolymsk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Norfolk Island",
    timezoneIdentifier: "Pacific/Norfolk",
    mapping: ["Pacific/Norfolk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Sakhalin",
    timezoneIdentifier: "Asia/Sakhalin",
    mapping: ["Asia/Magadan", "Asia/Sakhalin", "Asia/Srednekolymsk"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Solomon Islands, New Caledonia",
    timezoneIdentifier: "Pacific/Guadalcanal",
    mapping: ["Pacific/Guadalcanal", "Pacific/Pohnpei", "Pacific/Ponape"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Anadyr, Petropavlovsk-Kamchatsky",
    timezoneIdentifier: "Asia/Kamchatka",
    mapping: ["Asia/Anadyr", "Asia/Kamchatka"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Auckland, Wellington",
    timezoneIdentifier: "Pacific/Auckland",
    mapping: ["Pacific/Auckland", "NZ", "Antarctica/McMurdo", "Antarctica/South_Pole"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Coordinated Universal Time+12",
    timezoneIdentifier: "Etc/GMT-12",
    mapping: ["Etc/GMT-12"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Fiji",
    timezoneIdentifier: "Pacific/Fiji",
    mapping: ["Pacific/Fiji"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Chatham Islands",
    timezoneIdentifier: "Pacific/Chatham",
    mapping: ["Pacific/Chatham", "NZ-CHAT"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Coordinated Universal Time+13",
    timezoneIdentifier: "Etc/GMT-13",
    mapping: ["Etc/GMT-13"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Nuku'alofa",
    timezoneIdentifier: "Pacific/Tongatapu",
    mapping: ["Pacific/Tongatapu"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Samoa",
    timezoneIdentifier: "Pacific/Apia",
    mapping: ["Pacific/Apia"],
  },
  {
    name: "(UTC${TZ_OFFSET}) Kiritimati Island",
    timezoneIdentifier: "Pacific/Kiritimati",
    mapping: ["Pacific/Kiritimati"],
  },
].map((timezone) => {
  timezone.name = timezone.name.replace("${TZ_OFFSET}", dayjs().tz(timezone.timezoneIdentifier).format("Z"));

  return timezone;
});

/**
 * List **original** timezones in windows using cmd: tzutil /l
 * @property name : for displaying
 * @property timezoneIdentifier : for sending to the backend
 */
export const TIMEZONES_WINDOWS = [
  {
    name: "(UTC${TZ_OFFSET}) International Date Line West",
    timezoneIdentifier: "Etc/GMT+12",
  },
  {
    name: "(UTC${TZ_OFFSET}) Coordinated Universal Time-11",
    timezoneIdentifier: "Etc/GMT+11",
  },
  {
    name: "(UTC${TZ_OFFSET}) Aleutian Islands",
    timezoneIdentifier: "America/Adak",
  },
  {
    name: "(UTC${TZ_OFFSET}) Hawaii",
    timezoneIdentifier: "Pacific/Honolulu",
  },
  {
    name: "(UTC${TZ_OFFSET}) Marquesas Islands",
    timezoneIdentifier: "Pacific/Marquesas",
  },
  {
    name: "(UTC${TZ_OFFSET}) Alaska",
    timezoneIdentifier: "America/Anchorage",
  },
  {
    name: "(UTC${TZ_OFFSET}) Coordinated Universal Time-09",
    timezoneIdentifier: "Etc/GMT+9",
  },
  {
    name: "(UTC${TZ_OFFSET}) Baja California",
    timezoneIdentifier: "America/Tijuana",
  },
  {
    name: "(UTC${TZ_OFFSET}) Coordinated Universal Time-08",
    timezoneIdentifier: "Etc/GMT+8",
  },
  {
    name: "(UTC${TZ_OFFSET}) Pacific Time (US and Canada)",
    timezoneIdentifier: "America/Los_Angeles",
  },
  {
    name: "(UTC${TZ_OFFSET}) Arizona",
    timezoneIdentifier: "America/Phoenix",
  },
  {
    name: "(UTC${TZ_OFFSET}) La Paz, Mazatlan",
    timezoneIdentifier: "America/Chihuahua",
  },
  {
    name: "(UTC${TZ_OFFSET}) Mountain Time (US and Canada)",
    timezoneIdentifier: "America/Denver",
  },
  {
    name: "(UTC${TZ_OFFSET}) Yukon",
    timezoneIdentifier: "America/Whitehorse",
  },
  {
    name: "(UTC${TZ_OFFSET}) Central America",
    timezoneIdentifier: "America/Guatemala",
  },
  {
    name: "(UTC${TZ_OFFSET}) Central Time (US and Canada)",
    timezoneIdentifier: "America/Chicago",
  },
  {
    name: "(UTC${TZ_OFFSET}) Easter Island",
    timezoneIdentifier: "Pacific/Easter",
  },
  {
    name: "(UTC${TZ_OFFSET}) Guadalajara, Mexico City, Monterrey",
    timezoneIdentifier: "America/Mexico_City",
  },
  {
    name: "(UTC${TZ_OFFSET}) Saskatchewan",
    timezoneIdentifier: "America/Regina",
  },
  {
    name: "(UTC${TZ_OFFSET}) Bogota, Lima, Quito, Rio Branco",
    timezoneIdentifier: "America/Bogota",
  },
  {
    name: "(UTC${TZ_OFFSET}) Chetumal",
    timezoneIdentifier: "America/Cancun",
  },
  {
    name: "(UTC${TZ_OFFSET}) Eastern Time (US and Canada)",
    timezoneIdentifier: "America/New_York",
  },
  {
    name: "(UTC${TZ_OFFSET}) Haiti",
    timezoneIdentifier: "America/Port-au-Prince",
  },
  {
    name: "(UTC${TZ_OFFSET}) Havana",
    timezoneIdentifier: "America/Havana",
  },
  {
    name: "(UTC${TZ_OFFSET}) Indiana (East)",
    timezoneIdentifier: "America/Indiana/Indianapolis",
  },
  {
    name: "(UTC${TZ_OFFSET}) Turks and Caicos",
    timezoneIdentifier: "America/Grand_Turk",
  },
  {
    name: "(UTC${TZ_OFFSET}) Asuncion",
    timezoneIdentifier: "America/Asuncion",
  },
  {
    name: "(UTC${TZ_OFFSET}) Atlantic Time (Canada)",
    timezoneIdentifier: "America/Halifax",
  },
  {
    name: "(UTC${TZ_OFFSET}) Caracas",
    timezoneIdentifier: "America/Caracas",
  },
  {
    name: "(UTC${TZ_OFFSET}) Cuiaba",
    timezoneIdentifier: "America/Cuiaba",
  },
  {
    name: "(UTC${TZ_OFFSET}) Georgetown, La Paz, Manaus, San Juan",
    timezoneIdentifier: "America/La_Paz",
  },
  {
    name: "(UTC${TZ_OFFSET}) Santiago",
    timezoneIdentifier: "America/Santiago",
  },
  {
    name: "(UTC${TZ_OFFSET}) Newfoundland",
    timezoneIdentifier: "America/St_Johns",
  },
  {
    name: "(UTC${TZ_OFFSET}) Araguaina",
    timezoneIdentifier: "America/Araguaina",
  },
  {
    name: "(UTC${TZ_OFFSET}) Brasilia",
    timezoneIdentifier: "America/Sao_Paulo",
  },
  {
    name: "(UTC${TZ_OFFSET}) Cayenne, Fortaleza",
    timezoneIdentifier: "America/Fortaleza",
  },
  {
    name: "(UTC${TZ_OFFSET}) City of Buenos Aires",
    timezoneIdentifier: "America/Argentina/Buenos_Aires",
  },
  {
    name: "(UTC${TZ_OFFSET}) Greenland",
    timezoneIdentifier: "America/Godthab",
  },
  {
    name: "(UTC${TZ_OFFSET}) Montevideo",
    timezoneIdentifier: "America/Montevideo",
  },
  {
    name: "(UTC${TZ_OFFSET}) Punta Arenas",
    timezoneIdentifier: "America/Punta_Arenas",
  },
  {
    name: "(UTC${TZ_OFFSET}) Saint Pierre and Miquelon",
    timezoneIdentifier: "America/Miquelon",
  },
  {
    name: "(UTC${TZ_OFFSET}) Salvador",
    timezoneIdentifier: "America/Bahia",
  },
  {
    name: "(UTC${TZ_OFFSET}) Coordinated Universal Time-02",
    timezoneIdentifier: "Etc/GMT+2",
  },
  {
    name: "(UTC${TZ_OFFSET}) Azores",
    timezoneIdentifier: "Atlantic/Azores",
  },
  {
    name: "(UTC${TZ_OFFSET}) Cabo Verde Is.",
    timezoneIdentifier: "Atlantic/Cape_Verde",
  },
  {
    name: "(UTC) Coordinated Universal Time",
    timezoneIdentifier: "Etc/GMT",
  },
  {
    name: "(UTC${TZ_OFFSET}) Dublin, Edinburgh, Lisbon, London",
    timezoneIdentifier: "Europe/London",
  },
  {
    name: "(UTC${TZ_OFFSET}) Monrovia, Reykjavik",
    timezoneIdentifier: "Africa/Monrovia",
  },
  {
    name: "(UTC${TZ_OFFSET}) Sao Tome",
    timezoneIdentifier: "Africa/Sao_Tome",
  },
  {
    name: "(UTC${TZ_OFFSET}) Casablanca",
    timezoneIdentifier: "Africa/Casablanca",
  },
  {
    name: "(UTC${TZ_OFFSET}) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
    timezoneIdentifier: "Europe/Amsterdam",
  },
  {
    name: "(UTC${TZ_OFFSET}) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
    timezoneIdentifier: "Europe/Belgrade",
  },
  {
    name: "(UTC${TZ_OFFSET}) Brussels, Copenhagen, Madrid, Paris",
    timezoneIdentifier: "Europe/Brussels",
  },
  {
    name: "(UTC${TZ_OFFSET}) Sarajevo, Skopje, Warsaw, Zagreb",
    timezoneIdentifier: "Europe/Sarajevo",
  },
  {
    name: "(UTC${TZ_OFFSET}) West Central Africa",
    timezoneIdentifier: "Africa/Lagos",
  },
  {
    name: "(UTC${TZ_OFFSET}) Athens, Bucharest",
    timezoneIdentifier: "Europe/Athens",
  },
  {
    name: "(UTC${TZ_OFFSET}) Beirut",
    timezoneIdentifier: "Asia/Beirut",
  },
  {
    name: "(UTC${TZ_OFFSET}) Cairo",
    timezoneIdentifier: "Africa/Cairo",
  },
  {
    name: "(UTC${TZ_OFFSET}) Chisinau",
    timezoneIdentifier: "Europe/Chisinau",
  },
  {
    name: "(UTC${TZ_OFFSET}) Damascus",
    timezoneIdentifier: "Asia/Damascus",
  },
  {
    name: "(UTC${TZ_OFFSET}) Gaza, Hebron",
    timezoneIdentifier: "Asia/Gaza",
  },
  {
    name: "(UTC${TZ_OFFSET}) Harare, Pretoria",
    timezoneIdentifier: "Africa/Harare",
  },
  {
    name: "(UTC${TZ_OFFSET}) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius",
    timezoneIdentifier: "Europe/Helsinki",
  },
  {
    name: "(UTC${TZ_OFFSET}) Jerusalem",
    timezoneIdentifier: "Asia/Jerusalem",
  },
  {
    name: "(UTC${TZ_OFFSET}) Juba",
    timezoneIdentifier: "Africa/Juba",
  },
  {
    name: "(UTC${TZ_OFFSET}) Kaliningrad",
    timezoneIdentifier: "Europe/Kaliningrad",
  },
  {
    name: "(UTC${TZ_OFFSET}) Khartoum",
    timezoneIdentifier: "Africa/Khartoum",
  },
  {
    name: "(UTC${TZ_OFFSET}) Tripoli",
    timezoneIdentifier: "Africa/Tripoli",
  },
  {
    name: "(UTC${TZ_OFFSET}) Windhoek",
    timezoneIdentifier: "Africa/Windhoek",
  },
  {
    name: "(UTC${TZ_OFFSET}) Amman",
    timezoneIdentifier: "Asia/Amman",
  },
  {
    name: "(UTC${TZ_OFFSET}) Baghdad",
    timezoneIdentifier: "Asia/Baghdad",
  },
  {
    name: "(UTC${TZ_OFFSET}) Istanbul",
    timezoneIdentifier: "Europe/Istanbul",
  },
  {
    name: "(UTC${TZ_OFFSET}) Kuwait, Riyadh",
    timezoneIdentifier: "Asia/Riyadh",
  },
  {
    name: "(UTC${TZ_OFFSET}) Minsk",
    timezoneIdentifier: "Europe/Minsk",
  },
  {
    name: "(UTC${TZ_OFFSET}) Moscow, St. Petersburg",
    timezoneIdentifier: "Europe/Moscow",
  },
  {
    name: "(UTC${TZ_OFFSET}) Nairobi",
    timezoneIdentifier: "Africa/Nairobi",
  },
  {
    name: "(UTC${TZ_OFFSET}) Volgograd",
    timezoneIdentifier: "Europe/Volgograd",
  },
  {
    name: "(UTC${TZ_OFFSET}) Tehran",
    timezoneIdentifier: "Asia/Tehran",
  },
  {
    name: "(UTC${TZ_OFFSET}) Abu Dhabi, Muscat",
    timezoneIdentifier: "Asia/Dubai",
  },
  {
    name: "(UTC${TZ_OFFSET}) Astrakhan, Ulyanovsk",
    timezoneIdentifier: "Europe/Astrakhan",
  },
  {
    name: "(UTC${TZ_OFFSET}) Baku",
    timezoneIdentifier: "Asia/Baku",
  },
  {
    name: "(UTC${TZ_OFFSET}) Izhevsk, Samara",
    timezoneIdentifier: "Europe/Samara",
  },
  {
    name: "(UTC${TZ_OFFSET}) Port Louis",
    timezoneIdentifier: "Indian/Mauritius",
  },
  {
    name: "(UTC${TZ_OFFSET}) Saratov",
    timezoneIdentifier: "Europe/Saratov",
  },
  {
    name: "(UTC${TZ_OFFSET}) Tbilisi",
    timezoneIdentifier: "Asia/Tbilisi",
  },
  {
    name: "(UTC${TZ_OFFSET}) Yerevan",
    timezoneIdentifier: "Asia/Yerevan",
  },
  {
    name: "(UTC${TZ_OFFSET}) Kabul",
    timezoneIdentifier: "Asia/Kabul",
  },
  {
    name: "(UTC${TZ_OFFSET}) Ashgabat, Tashkent",
    timezoneIdentifier: "Asia/Ashgabat",
  },
  {
    name: "(UTC${TZ_OFFSET}) Ekaterinburg",
    timezoneIdentifier: "Asia/Yekaterinburg",
  },
  {
    name: "(UTC${TZ_OFFSET}) Islamabad, Karachi",
    timezoneIdentifier: "Asia/Karachi",
  },
  {
    name: "(UTC${TZ_OFFSET}) Qyzylorda",
    timezoneIdentifier: "Asia/Qyzylorda",
  },
  {
    name: "(UTC${TZ_OFFSET}) Chennai, Kolkata, Mumbai, New Delhi",
    timezoneIdentifier: "Asia/Kolkata",
  },
  {
    name: "(UTC${TZ_OFFSET}) Sri Jayawardenepura",
    timezoneIdentifier: "Asia/Colombo",
  },
  {
    name: "(UTC${TZ_OFFSET}) Kathmandu",
    timezoneIdentifier: "Asia/Kathmandu",
  },
  {
    name: "(UTC${TZ_OFFSET}) Astana",
    timezoneIdentifier: "Asia/Almaty",
  },
  {
    name: "(UTC${TZ_OFFSET}) Dhaka",
    timezoneIdentifier: "Asia/Dhaka",
  },
  {
    name: "(UTC${TZ_OFFSET}) Omsk",
    timezoneIdentifier: "Asia/Omsk",
  },
  {
    name: "(UTC${TZ_OFFSET}) Yangon (Rangoon)",
    timezoneIdentifier: "Asia/Yangon",
  },
  {
    name: "(UTC${TZ_OFFSET}) Bangkok, Hanoi, Jakarta",
    timezoneIdentifier: "Asia/Bangkok",
  },
  {
    name: "(UTC${TZ_OFFSET}) Barnaul, Gorno-Altaysk",
    timezoneIdentifier: "Asia/Barnaul",
  },
  {
    name: "(UTC${TZ_OFFSET}) Hovd",
    timezoneIdentifier: "Asia/Hovd",
  },
  {
    name: "(UTC${TZ_OFFSET}) Krasnoyarsk",
    timezoneIdentifier: "Asia/Krasnoyarsk",
  },
  {
    name: "(UTC${TZ_OFFSET}) Novosibirsk",
    timezoneIdentifier: "Asia/Novosibirsk",
  },
  {
    name: "(UTC${TZ_OFFSET}) Tomsk",
    timezoneIdentifier: "Asia/Tomsk",
  },
  {
    name: "(UTC${TZ_OFFSET}) Beijing, Chongqing, Hong Kong, Urumqi",
    timezoneIdentifier: "Asia/Shanghai",
  },
  {
    name: "(UTC${TZ_OFFSET}) Irkutsk",
    timezoneIdentifier: "Asia/Irkutsk",
  },
  {
    name: "(UTC${TZ_OFFSET}) Kuala Lumpur, Singapore",
    timezoneIdentifier: "Asia/Kuala_Lumpur",
  },
  {
    name: "(UTC${TZ_OFFSET}) Perth",
    timezoneIdentifier: "Australia/Perth",
  },
  {
    name: "(UTC${TZ_OFFSET}) Taipei",
    timezoneIdentifier: "Asia/Taipei",
  },
  {
    name: "(UTC${TZ_OFFSET}) Ulaanbaatar",
    timezoneIdentifier: "Asia/Ulaanbaatar",
  },
  {
    name: "(UTC${TZ_OFFSET}) Eucla",
    timezoneIdentifier: "Australia/Eucla",
  },
  {
    name: "(UTC${TZ_OFFSET}) Chita",
    timezoneIdentifier: "Asia/Chita",
  },
  {
    name: "(UTC${TZ_OFFSET}) Osaka, Sapporo, Tokyo",
    timezoneIdentifier: "Asia/Tokyo",
  },
  {
    name: "(UTC${TZ_OFFSET}) Pyongyang",
    timezoneIdentifier: "Asia/Pyongyang",
  },
  {
    name: "(UTC${TZ_OFFSET}) Seoul",
    timezoneIdentifier: "Asia/Seoul",
  },
  {
    name: "(UTC${TZ_OFFSET}) Yakutsk",
    timezoneIdentifier: "Asia/Yakutsk",
  },
  {
    name: "(UTC${TZ_OFFSET}) Adelaide",
    timezoneIdentifier: "Australia/Adelaide",
  },
  {
    name: "(UTC${TZ_OFFSET}) Darwin",
    timezoneIdentifier: "Australia/Darwin",
  },
  {
    name: "(UTC${TZ_OFFSET}) Brisbane",
    timezoneIdentifier: "Australia/Brisbane",
  },
  {
    name: "(UTC${TZ_OFFSET}) Canberra, Melbourne, Sydney",
    timezoneIdentifier: "Australia/Sydney",
  },
  {
    name: "(UTC${TZ_OFFSET}) Guam, Port Moresby",
    timezoneIdentifier: "Pacific/Guam",
  },
  {
    name: "(UTC${TZ_OFFSET}) Hobart",
    timezoneIdentifier: "Australia/Hobart",
  },
  {
    name: "(UTC${TZ_OFFSET}) Vladivostok",
    timezoneIdentifier: "Asia/Vladivostok",
  },
  {
    name: "(UTC${TZ_OFFSET}) Lord Howe Island",
    timezoneIdentifier: "Australia/Lord_Howe",
  },
  {
    name: "(UTC${TZ_OFFSET}) Bougainville Island",
    timezoneIdentifier: "Pacific/Bougainville",
  },
  {
    name: "(UTC${TZ_OFFSET}) Chokurdakh",
    timezoneIdentifier: "Asia/Srednekolymsk",
  },
  {
    name: "(UTC${TZ_OFFSET}) Magadan",
    timezoneIdentifier: "Asia/Magadan",
  },
  {
    name: "(UTC${TZ_OFFSET}) Norfolk Island",
    timezoneIdentifier: "Pacific/Norfolk",
  },
  {
    name: "(UTC${TZ_OFFSET}) Sakhalin",
    timezoneIdentifier: "Asia/Sakhalin",
  },
  {
    name: "(UTC${TZ_OFFSET}) Solomon Islands, New Caledonia",
    timezoneIdentifier: "Pacific/Guadalcanal",
  },
  {
    name: "(UTC${TZ_OFFSET}) Anadyr, Petropavlovsk-Kamchatsky",
    timezoneIdentifier: "Asia/Kamchatka",
  },
  {
    name: "(UTC${TZ_OFFSET}) Auckland, Wellington",
    timezoneIdentifier: "Pacific/Auckland",
  },
  {
    name: "(UTC${TZ_OFFSET}) Coordinated Universal Time+12",
    timezoneIdentifier: "Etc/GMT-12",
  },
  {
    name: "(UTC${TZ_OFFSET}) Fiji",
    timezoneIdentifier: "Pacific/Fiji",
  },
  {
    name: "(UTC${TZ_OFFSET}) Chatham Islands",
    timezoneIdentifier: "Pacific/Chatham",
  },
  {
    name: "(UTC${TZ_OFFSET}) Coordinated Universal Time+13",
    timezoneIdentifier: "Etc/GMT-13",
  },
  {
    name: "(UTC${TZ_OFFSET}) Nuku'alofa",
    timezoneIdentifier: "Pacific/Tongatapu",
  },
  {
    name: "(UTC${TZ_OFFSET}) Samoa",
    timezoneIdentifier: "Pacific/Apia",
  },
  {
    name: "(UTC${TZ_OFFSET}) Kiritimati Island",
    timezoneIdentifier: "Pacific/Kiritimati",
  },
].map((timezone) => {
  timezone.name = timezone.name.replace("${TZ_OFFSET}", dayjs().tz(timezone.timezoneIdentifier).format("Z"));

  return timezone;
});
