export const config = {
  HEIGHT_MARKER_INFO: 480,
  HEIGHT_STATUS_INFO_LIST: 0,
  HEIGHT_TYPEID_ITEM: 21,
  MARGIN_TYPEID: 8,
  MAX_HEIGHT_TYPEID_LIST: 192,
  HEIGHT_AREA_STORE: 44,
  PX_TO_REM: 16,
  MAX_TYPEID_ITEM_DISPLAY: 9,
};
